# We don't really need it (at least for now)
# before_install:
# - sudo apt-get update -qq
# - sudo apt-get install ftp -qq

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/fzipp/gocyclo

language: go

# We're building for the two last versions
go:
  - 1.7.x
  - 1.8.x

script:
  - ./.check-fmt.sh
  - gocyclo -over 15 .
  - go test -v ./...
