# This config allows to listen locally and bring a very restricted number of ports

[server]
public_host = "127.0.0.1"

[server.passiveTransferPortRange]
start = 2122
end = 2123

[[users]]
user="test"
pass="test"
dir="shared"

