name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ 1.14.2 ] # , 1.13.10 
        include:
          - go: 1.14.2
            lint: true
            package: true
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Running golangci-lint
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
        if: matrix.lint

      # Install Go
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...

      - name: Test
        # We need GCC because of the "go test -race"
        # env:
        #   CGO_ENABLED: 0
        run: |
          apt-get update && apt-get install gcc -y
          go test -race -v ./...

