name: Docker test

on:
  schedule:
    # We want to run it every day
    - cron:  '*/5 * * * *'

jobs:
  test-docker-image:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    services:
      ftpserver:
        image: ftpserver/ftpserver
        ports:
          - 2121-2200:2121-2200

    steps:
      - name: Run sample
        env:
          SERVER_PORT: 2121
        run: |
          set -xe
          whoami
          sudo apt-get update
          sudo apt-get install netcat curl -y

          # Getting a file
          curl https://placekitten.com/2048/2048 -o kitty.jpg

          # Waiting for server to be ready
          while ! nc -z localhost ${SERVER_PORT} </dev/null; do sleep 1; done

          # Upload a file
          curl -P - -T kitty.jpg ftp://test:test@localhost:${SERVER_PORT}/remote.jpg

          # Download a file
          curl -P - ftp://test:test@localhost:2121/remote.jpg -o remote.jpg

          # Checking that the output file exists
          if [ ! -f remote.jpg ]; then
            exit 1
          fi

          # Comparing file contents
          diff kitty.jpg remote.jpg
