name: Docker image generation

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    
    - name: Build
      run: go build

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ftpserver/ftpserver
        username: ftpserver
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
